# Generated by Django 5.1.4 on 2024-12-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penthouse',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
