# Generated by Django 5.1.4 on 2024-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_apartment_description_penthouse_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='payment_process',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='penthouse',
            name='payment_process',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='payment_process',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
