# Generated by Django 5.0.6 on 2024-12-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PropertyImage',
        ),
    ]
