# Generated by Django 5.1.4 on 2024-12-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_rename_image_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='penthouse',
            name='image',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='image',
        ),
    ]
