# Generated by Django 5.1.4 on 2024-12-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_apartment_code_penthouse_code_villa_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvisit',
            name='user',
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='user_name',
            field=models.CharField(default='Guest', max_length=200),
        ),
        migrations.AddField(
            model_name='propertyvisit',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
